#default_responders = ""

[status]
#production = [ "PRODUCTION", "DISABLED", "REMOVED" ]
#safe = [ "DESIGN" ]

[promotion]
#enabled = true
#promotion_target = "PRODUCTION"

[proxy]
#proxy_user = "$PROXY_USER"
#proxy_password = "$PROXY_PASSWORD"
#proxy_host = "$PROXY_HOST"
#proxy_port = "$PROXY_PORT"

# If enabled, updates a lookup continuously with MDR Data. Often useful to
# have access to MDR Data directly on external systems, e.g. for alert enriching
[metadata_lookup]
#enabled = false
#name = ""
#systems = ["splunk"]